# Generated by Django 3.1.7 on 2021-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField()),
                ('name', models.TextField()),
                ('sys_argv', models.TextField(null=True, verbose_name='sys.argv')),
                ('args', models.TextField(null=True)),
                ('options', models.TextField(null=True)),
                ('exc_type', models.TextField(verbose_name='type')),
                ('exc_value', models.TextField(verbose_name='value')),
                ('exc_traceback', models.TextField(verbose_name='traceback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'db_table': 'django_command_error',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['app'], name='django_comm_app_7cd7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['name'], name='django_comm_name_0b0042_idx'),
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['exc_type'], name='django_comm_exc_typ_242d98_idx'),
        ),
        migrations.AddIndex(
            model_name='error',
            index=models.Index(fields=['-created_at'], name='django_comm_created_e82399_idx'),
        ),
    ]
